### PR TITLE
Log head branch changes instead of aborting

### LINKED ISSUE #38: Catch rebase aborted errors
This error should not fail the build, but it should be logged and continue.

```
##[error]Error: Error while rebasing for {"ownerName":"Label305","repoName":"MyRepo","number":425,"draft":false,"rebaseable":true,"mergeableState":"behind","labels":["autorebase:opt-in"]}: Error: Rebase aborted because the head branch changed.
```

### PR DESCRIPTION
**Pull request by nhaarman**
Fixes #38

### CODE REVIEW

**Review by JBlaak — APPROVED** [review]

File: src/index.ts [hunk 1]
```diff
@@ -21,7 +23,7 @@ async function run(): Promise<void> {
         const eligiblePullRequestsRetriever: EligiblePullRequestsRetriever = new TestableEligiblePullRequestsRetriever(
             openPullRequestsProvider,
         );
-        const rebaser = new Rebaser(github);
+        const rebaser = new Rebaser(new RealGithubRebase((github as unknown) as Octokit));
```
Comment (JBlaak) [inline src/index.ts:26]: There's no typing for `github`?
